# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  credentials = file("../credentials/terraform-backend-XXX-XXX.json")
  project     = "terraform-backend-XXX"
  region      = "us-west1"
}
