# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
output "prod_barebone_project_id" {
  value = module.prod_bb_project.project_id
  description = "The ID of the barebone production project."
}

output "prod_k8s_project_id" {
  value = module.prod_k8s_project.project_id
  description = "The ID of the k8s production project."
}
