# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "org_id" {
  description = "The organization ID"
  type        = string
}

variable "prod_folder_name" {
  description = "The production folder name"
  type        = list(string)
}

variable "billing_id" {
  description = "The billing ID"
  type        = string
}

variable "prod_project_apis" {
  type = map(string)
}
