# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
output "prod_barebone_sa_email" {
  value = google_service_account.vpc_vm_service_account.email
  description = "The SA email for barebone production project."
}
