# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  credentials = file("../../credentials/terraform-backend-XXX-XXX.json")
  project     = "production"
  region      = "us-west1"
}
