# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  region = "us-west1"
  project = var.mgmt_project_id
}

provider "google-beta" {
  region = "us-west1"
  project = var.mgmt_project_id
}
