# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
data "terraform_remote_state" "production_project_remote_data" {
  backend = "gcs"

  config = {
    bucket = "server-infrastructure"
    prefix = "prod/01-prod-projects"
  }
}
