# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
data "terraform_remote_state" "root_folder_remote_data" {
  backend = "gcs"

  config = {
    bucket = "server-infrastructure"
    prefix = "00-folders"
  }
}
