# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
output "prod_barebone_folder_id" {
  value = google_folder.production_barebone.id
  description = "The ID of the barebone prod folder."
}

output "prod_k8s_folder_id" {
  value = google_folder.production_k8s.id
  description = "The ID of the k8s prod folder."
}
